Micromata BorgBackup-Butler
===========================
Micromata GmbH, Kai Reinhard
:toc:
:toclevels: 4

Copyright (C) 2018

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Configuration


~/.borgbutler/borgbutler-config.json
[source,json]
----
{
  "cache_archive_content_max_disc_size_mb" : 1000,
  "repo-configs" : [ {
    "display_name" : "My-Laptop-Local-Backup",
    "repo"         : "/Volumes/backup/my-laptop-backup",
  },
  {
    "display_name"    : "My-Laptop-Remote-Backup",
    "repo"            : "ssh://backup.acme.com/./backups/my-laptop",
    "passwordCommand" : "security find-generic-password -a $USER -s borg-passphrase -w",
    "rsh"             : "ssh -i /Users/horst/.ssh/acme_rsa"
  } ]
}
----
* `cache_max_disc_size_mb` specifies the cache size BorgButler may use for caching borg results (such as repository
information, archive information and also file list of archive content).
* `repo-configs`: You may add a list of all your repos with the borg variables. The name is only used for displaying
purposes.

== For developers

=== Lombok required
==== Installing Lombok in IntelliJ
[.text-center]
https://github.com/mplushnikov/lombok-intellij-plugin[Lombok Intellij plugin description^] +
[.text-left]
Or go to
[.text-center]
https://projectlombok.org/[Lombok home page^] +
[.text-left]

=== Work with borgbutler-server
==== npm without hot code replacement
1. `cd borgbutler-webapp`
2. `npm install`
3. `npm start`
4. `gradle gradle npmBuild`
5. Start `de.micromata.borgbutler.server.Main`

==== npm with hot code replacement

1. `cd borgbutler-webapp`
2. `npm install`
3. `npm start`
5. Start `de.micromata.borgbutler.server.Main`

=== Ideas
==== 2 factor authentication
https://github.com/j256/two-factor-auth

=== Install server
==== Debian
