= Micromata BorgBackup-Butler
Micromata GmbH, Kai Reinhard
:toc:
:toclevels: 4

Copyright (C) 2018-2021

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Why?

* Accessing your borg backups in an very convenient and fast way.
* Caches remote repo archive information for fast browsing.
* Differ functionality to see the differences of backups (files, directories etc.)

== Quick start
=== Docker

BorgButler working directory `$HOME/.borgbutler` is assumed, but you may define any other.

1. `docker run -v $HOME/.borgbutler:/Borgbutler -p 127.0.0.1:9042:9042 --name borgbuttler kreinhard/borgbutler` (exporting of `.ssh` is useful for ssh remotes, otherwise skip this setting.)
2. Stopping: simly click `CTRL-C`.
3. Restart: `docker start`
4. Stop: `docker stop`

Enjoy BorgButler by opening your browser: http://localhost:9042

You may refer the log file through the web browser or in `$HOME/.borgbutler/borgbutler.log`.


=== Starting from sources
1. `gradle clean distZip`
2. Unzip `borgbutler-server/build/distributions/borgbutler-server-<version>.zip`
3. Run `bin/borgbutler-server` or `bin/borgbutler-server.bat`.

Enjoy BorgButler by opening your browser: http://localhost:9042

== Further informatino

=== Configuration
==== Backups of configuration files

You may configure and initialize your repositories by the BorgButler app. The config file is generated by BorgButler. Before
saving a new configuration BorgButler stores a copy of the current configuration in the backup dir: `~/.borgbutler/backup/`.

=== Profiling heap, cpu and everything using JProfiler
JProfiler is an excellent tool for analysing your software. BorgButler was optimized regarding heap memory and CPU usage by
using https://www.ej-technologies.com/products/jprofiler/overview.html[JProfiler from EJ Technologies^]
