export const LOG_VIEW_RELOADED = 'LOG_VIEW_RELOADED';
export const LOG_VIEW_REQUEST_RELOAD = 'LOG_VIEW_REQUEST_RELOAD';
export const LOG_VIEW_FAILED_RELOAD = 'LOG_VIEW_FAILED_RELOAD';
export const LOG_VIEW_CHANGE_FILTER = 'LOG_VIEW_CHANGE_FILTER';

export const VERSION_REQUEST_RELOAD = 'VERSION_REQUEST_RELOAD';
export const VERSION_RELOADED = 'VERSION_RELOADED';
export const VERSION_RELOAD_FAILED = 'VERSION_RELOAD_FAILED';
